name: Check ESLint

on:
  push:

jobs:
  check-eslint:
    runs-on: ubuntu-latest
    name: Check ESLint

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run ESLint
        run: yarn lint
