name: Test All Package Installation

on:
  push:

jobs:
  check-package-manager:
    runs-on: ubuntu-latest
    name: Package Installation and Linting

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: yarn install

      - name: Run ESLint
        run: npm run lint
